### ISSUE TITLE
Request for Publication of Article

### ISSUE THREAD

**Issue by ihopenot** [lzto/afl-proxy#1]
Hello,

I am a student at Huazhong University of Science and Technology in China, currently working on a project similar to yours. I am very interested in reading your article titled "DEVFUZZ: Automatic Device Model-Guided Device Driver Fuzzing." However, I encountered difficulty accessing it as SP2023 requires a Computer Society VIP subscription, which unfortunately, our university has not yet obtained.

I would greatly appreciate it if you could kindly provide me with access to the article or share a copy of it. Reading your research would significantly contribute to my project and deepen my understanding of the subject matter.

Thank you for your consideration, and I look forward to your response.

**Comment by lzto** [comment]
Please leave your email address I will send it to your email.

**Comment by ihopenot** [comment]
984430652@qq.com
Thanks alot.
